name: Test

on:
  push:
    branches:
      - v2.x
  pull_request:
    branches:
      - v2.x

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

    - name: Install dependencies
      run: composer install

    - name: Copy .env.example to .env
      run: cp .env.example .env

    - name: Generate application key
      run: php artisan key:generate

    - name: Install dependencies and build assets
      run: |
        composer update
        composer install --no-progress --no-suggest --prefer-dist
        npm install
        sudo npm run build

    - name: Run tests
      run: vendor/bin/phpunit
